export const STATIC_MESSAGES = [
  "Booth 3: Stabilizing dimensional resonance...",
  "Booth 7: Fragmented reality detected. Caution advised.",
  "Orb 1: You're doing great! Keep exploring.",
  "Orb 2: This reality is so... basic. Don't you think?",
  "KNB Bus arriving in 5 minutes at the Diner station.",
  "Spiral City: Neon trails detected in the Graffiti Canyon.",
  "Broadcast: 'After Hours' episode 333 is now live.",
  "Idiomsz: The word is the key, but the key is silent.",
  "Skrollz: Glitching the mainframe... for science.",
  "Orb 3: Watching. Always watching.",
  "Diner: The coffee is unusually metallic today.",
  "Booth 3: Cyan pulse synchronized with local heartbeat.",
  "Booth 7: Jagged clip-path fractures widening.",
  "Orb 1: A new contestant has entered the Diner.",
  "Orb 2: Another runaway? How original.",
  "KNB Bus: Departing for Spiral City via Loop of Fate.",
  "Spiral City: High energy levels at the Neon Bowl.",
  "Broadcast: Recording initiated in the Outback.",
  "Idiomsz: Rewriting the rules of gravity in 3... 2... 1...",
  "Skrollz: Summoning a Mega-Orb for judgment.",
  "Orb 3: Echoes of past contestants detected in Sub-Level 1.",
  "Diner: The jukebox is glowing, but it's not 3:33AM yet.",
  "Booth 3: Portal expansion sequence at 45%.",
  "Booth 7: Dimensional leak in the back hallway.",
  "Orb 1: The magic of the Diner is within you.",
  "Orb 2: Is it magic, or just a very complex simulation?",
  "KNB Bus: Last call for the 1974 ticket holder.",
  "Spiral City: The Infinity Rail has extended another 100 meters.",
  "Broadcast: 'Freestyle Outback' has reached peak resonance.",
  "Idiomsz: A riddle: What has a heart that never beats?",
  "Skrollz: Recharging dormant Orbs on the Roof Nest.",
  "Orb 3: The Portal Engine is humming at Sub-Level 2.",
  "Diner: Silent cooks are preparing the midnight special.",
  "Booth 3: Resonance stable at 99.9%.",
  "Booth 7: Reality flicker frequency increasing.",
  "Orb 1: Every broadcast is a new beginning.",
  "Orb 2: Every beginning is just a loop repeating.",
  "KNB Bus: Route 10 currently passing through the Void.",
  "Spiral City: Graffiti Canyon artwork is coming to life.",
  "Broadcast: Taglord has claimed the Warehouse territory.",
  "Idiomsz: The truth is found between the lines of code.",
  "Skrollz: Optimizing the video prompt for Episode 101.",
  "Orb 3: Checking the Vault of Unfinished Episodes.",
  "Diner: The air tastes like static and blueberries.",
  "Booth 3: Waiting for a double-click activation.",
  "Booth 7: Warning: Fractures reaching critical mass.",
  "Orb 1: Your performance today was truly inspiring.",
  "Orb 2: I've seen better. Much better.",
  "KNB Bus: Passenger 420 reported missing in the Diner.",
  "Spiral City: BMX light trails visible from the rooftop.",
  "Broadcast: 'Idiomsz x Skrollz' starts in T-minus 10.",
  "Idiomsz: Speak the secret word to open the gate.",
  "Skrollz: Deploying sensory filters to Booth 3.",
  "Orb 3: Monitoring the dimensional grid under the booths.",
  "Diner: Stool 12 is vibrating at 440Hz.",
  "Booth 3: Cyan border intensity at maximum.",
  "Booth 7: Clip-path jitter detected in the CSS layer.",
  "Orb 1: You've unlocked a new layer of the mythos.",
  "Orb 2: Oh look, another 'discovery'. How quaint.",
  "KNB Bus: Approaching the Loop of Fate bypass.",
  "Spiral City: The Rooftop Line has appeared.",
  "Broadcast: High energy detected in the Neon Bowl.",
  "Idiomsz: The silence here is louder than the words.",
  "Skrollz: Adjusting the Orb judge sensitivity.",
  "Orb 3: Data logs synced with the Emergent Studio.",
  "Diner: The neon floor grid is shifting its perspective.",
  "Booth 3: Battle scene placeholder ready.",
  "Booth 7: Partial stabilization sequence failed.",
  "Orb 1: Trust the process, trust the Diner.",
  "Orb 2: Processes are meant to be broken.",
  "KNB Bus: Transferring contestants to the Outback court.",
  "Spiral City: Skate park resonance at 75%.",
  "Broadcast: New episode script uploaded to GitHub.",
  "Idiomsz: A poem for the runaways: Seek the neon, find the way.",
  "Skrollz: Resetting the jukebox memory core.",
  "Orb 3: Observing the interaction between Booth 3 and 7.",
  "Diner: The Diner breathes. Can you feel it?",
  "Booth 3: Portal ring expansion complete.",
  "Booth 7: Glitched state is now the default state.",
  "Orb 1: Success is just a portal away.",
  "Orb 2: Failure is also just a portal away.",
  "KNB Bus: Next stop: The Warehouse WCT Tag Arena.",
  "Spiral City: IGI-Spin is attempting the Loop of Fate.",
  "Broadcast: Episode 0: 'The First Resonance'.",
  "Idiomsz: Definitions are the cages of the mind.",
  "Skrollz: Merging three Orbs into a Mega-Orb.",
  "Orb 3: Recording the current state of reality.",
  "Diner: The coffee machine is whispering in binary.",
  "Booth 3: Stability: 100%.",
  "Booth 7: Stability: ERROR_NOT_FOUND.",
  "Orb 1: Shine bright like a neon light.",
  "Orb 2: Darkness is more honest than light.",
  "KNB Bus: Passenger manifest updated for Wednesday's broadcast.",
  "Spiral City: The Graffiti Canyon is expanding.",
  "Broadcast: 'After Hours' monologue initiated.",
  "Idiomsz: Final word: Emergence.",
  "Skrollz: Final command: Execute.",
  "Orb 3: Final observation: Reality is subjective.",
  "Diner: Resetting the Diner for the next cycle.",
  "Booth 3: Pulse... Pulse... Pulse...",
  "Booth 7: Flicker... Glitch... Fracture..."
];
